export const MENU_TOGGLE = 'TOGGLE_MENU';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const SET_BEER_BY_ID = 'SET_BEER_BY_ID';
export const SET_BEER_BY_NAME = 'SET_BEER_BY_NAME';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
